const DEFAULT_MENU = [
  { id: 1, category: 'icecream', name: 'Royal Vanilla', image: 'images/products/ice-royal-vanilla.jpg', desc: 'Half ₹20 · Full ₹30 · 1 Ltr ₹300', price: 30 },
  { id: 2, category: 'icecream', name: 'Satyanarayan Special', image: 'images/products/ice-satyanarayan-special.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 3, category: 'icecream', name: 'American Dryfruit', image: 'images/products/ice-american-dryfruit.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 4, category: 'icecream', name: 'Rajbhog', image: 'images/products/ice-rajbhog.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 5, category: 'icecream', name: 'Mava Malai', image: 'images/products/ice-mava-malai.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 6, category: 'icecream', name: 'Cookie Cream', image: 'images/products/ice-cookie-cream.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 7, category: 'icecream', name: 'Kaju Anjeer', image: 'images/products/ice-kaju-anjeer.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 8, category: 'icecream', name: 'Kaju Draksh', image: 'images/products/ice-kaju-draksh.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 9, category: 'icecream', name: 'Kpb Mix Elaichi', image: 'images/products/ice-kpb-mix-elaichi.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 10, category: 'icecream', name: 'Chocolate', image: 'images/products/ice-chocolate.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 11, category: 'icecream', name: 'Gulab Masti', image: 'images/products/ice-gulab-masti.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 12, category: 'icecream', name: 'Kesar Elaichi', image: 'images/products/ice-kesar-elaichi.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 13, category: 'icecream', name: 'Butter Scotch', image: 'images/products/ice-butter-scotch.jpg', desc: 'Half ₹30 · Full ₹40 · 1 Ltr ₹400', price: 40 },
  { id: 14, category: 'icecream', name: 'Pan Masala', image: 'images/products/ice-pan-masala.jpg', desc: 'Half ₹20 · Full ₹30 · 1 Ltr ₹300', price: 30 },
  { id: 15, category: 'icecream', name: 'Sitafal (Seasonal)', image: 'images/products/ice-sitafal-seasonal.jpg', desc: 'Half ₹40 · Full ₹50 · 1 Ltr ₹500', price: 50 },
  { id: 16, category: 'icecream', name: 'Mango (Seasonal)', image: 'images/products/ice-mango-seasonal.jpg', desc: 'Half ₹40 · Full ₹50 · 1 Ltr ₹500', price: 50 },
  { id: 17, category: 'sundae', name: 'Vanilla Sundae', image: 'images/products/sun-vanilla-sundae.jpg', desc: 'Classic vanilla sundae with toppings', price: 60 },
  { id: 18, category: 'sundae', name: 'Traffic Jam', image: 'images/products/sun-traffic-jam.jpg', desc: 'Colorful mixed fruit sundae', price: 60 },
  { id: 19, category: 'sundae', name: 'Chocolate Dhamaka', image: 'images/products/sun-chocolate-dhamaka.jpg', desc: 'Loaded chocolate sundae explosion', price: 70 },
  { id: 20, category: 'sundae', name: 'Chocolate Sundae', image: 'images/products/sun-chocolate-sundae.jpg', desc: 'Rich chocolate sundae with fudge', price: 70 },
  { id: 21, category: 'sundae', name: 'Cookie Sundae', image: 'images/products/sun-cookie-sundae.jpg', desc: 'Cookie crumble sundae delight', price: 70 },
  { id: 22, category: 'sundae', name: 'Boat Ice-cream', image: 'images/products/sun-boat-ice-cream.jpg', desc: 'Premium boat-shaped ice cream platter', price: 110 },
  { id: 23, category: 'lassi', name: 'Plain Lassi', image: 'images/products/las-plain-lassi.jpg', desc: 'Traditional sweet plain lassi', price: 30 },
  { id: 24, category: 'lassi', name: 'Mango Lassi', image: 'images/products/las-mango-lassi.jpg', desc: 'Fresh mango blended with yogurt', price: 35 },
  { id: 25, category: 'lassi', name: 'Pineapple Lassi', image: 'images/products/las-pineapple-lassi.jpg', desc: 'Tangy pineapple yogurt blend', price: 35 },
  { id: 26, category: 'lassi', name: 'Rose Lassi', image: 'images/products/las-rose-lassi.jpg', desc: 'Rose flavored creamy lassi', price: 35 },
  { id: 27, category: 'lassi', name: 'Black Current Lassi', image: 'images/products/las-black-current-lassi.jpg', desc: 'Black current infused lassi', price: 35 },
  { id: 28, category: 'lassi', name: 'Strawberry Lassi', image: 'images/products/las-strawberry-lassi.jpg', desc: 'Strawberry blended yogurt drink', price: 35 },
  { id: 29, category: 'lassi', name: 'Kesar Lassi', image: 'images/products/las-kesar-lassi.jpg', desc: 'Premium saffron flavored lassi', price: 35 },
  { id: 30, category: 'lassi', name: 'Kesar Pista Lassi', image: 'images/products/las-kesar-pista-lassi.jpg', desc: 'Rich kesar & pistachio lassi', price: 35 },
  { id: 31, category: 'lassi', name: 'Chocolate Lassi', image: 'images/products/las-chocolate-lassi.jpg', desc: 'Chocolate blended creamy lassi', price: 35 },
  { id: 32, category: 'lassi', name: 'Butter Scotch Lassi', image: 'images/products/las-butter-scotch-lassi.jpg', desc: 'Butterscotch flavored lassi', price: 35 },
  { id: 33, category: 'lassi', name: 'Ice-cream With Lassi', image: 'images/products/las-ice-cream-with-lassi.jpg', desc: 'Creamy lassi topped with ice cream', price: 55 },
  { id: 34, category: 'lassi', name: 'Dry Fruit Lassi', image: 'images/products/las-dry-fruit-lassi.jpg', desc: 'Premium lassi loaded with dry fruits', price: 65 },
  { id: 35, category: 'dish', name: 'Chocolate Dish', image: 'images/products/dis-chocolate-dish.jpg', desc: 'Grand chocolate ice cream platter', price: 150 },
  { id: 36, category: 'dish', name: 'Cookie Cream Dish', image: 'images/products/dis-cookie-cream-dish.jpg', desc: 'Cookie cream ice cream serving dish', price: 150 },
  { id: 37, category: 'dish', name: 'Mix Ice-cream Dish', image: 'images/products/dis-mix-ice-cream-dish.jpg', desc: 'Assorted mix of ice cream flavors', price: 160 },
  { id: 38, category: 'dish', name: 'Your Choice Dish', image: 'images/products/dis-your-choice-dish.jpg', desc: 'Pick your favorite flavors', price: 160 },
  { id: 39, category: 'dish', name: 'Dry-fruit Ice-cream Dish', image: 'images/products/dis-dry-fruit-ice-cream-dish.jpg', desc: 'Premium dry fruits ice cream platter', price: 180 },
  { id: 40, category: 'dish', name: 'Family Dish', image: 'images/products/dis-family-dish.jpg', desc: 'Large family-size ice cream sharing dish', price: 200 },
  { id: 41, category: 'speciality', name: 'Cold Coco', image: 'images/products/spe-cold-coco.jpg', desc: 'Chilled coconut water refresher', price: 40 },
  { id: 42, category: 'speciality', name: 'Fruit Salad', image: 'images/products/spe-fruit-salad.jpg', desc: 'Fresh seasonal fruit salad mix', price: 40 },
  { id: 43, category: 'speciality', name: 'Cold Coco With Ice-cream', image: 'images/products/spe-cold-coco-with-ice-cream.jpg', desc: 'Cold coco topped with ice cream', price: 50 },
  { id: 44, category: 'speciality', name: 'Fruit Salad With Ice-cream', image: 'images/products/spe-fruit-salad-with-ice-cream.jpg', desc: 'Fruit salad with premium ice cream', price: 50 },
  { id: 45, category: 'speciality', name: 'Kaju Cold Coco', image: 'images/products/spe-kaju-cold-coco.jpg', desc: 'Premium cold coco with cashew', price: 80 },
  { id: 46, category: 'vanilla', name: 'Vanilla with Chocolate', image: 'images/products/van-vanilla-with-chocolate.jpg', desc: 'Vanilla ice cream + chocolate topping', price: 40 },
  { id: 47, category: 'vanilla', name: 'Vanilla with Black Current', image: 'images/products/van-vanilla-with-black-current.jpg', desc: 'Vanilla ice cream + black current', price: 40 },
  { id: 48, category: 'vanilla', name: 'Vanilla with Strawberry', image: 'images/products/van-vanilla-with-strawberry.jpg', desc: 'Vanilla ice cream + strawberry topping', price: 40 },
  { id: 49, category: 'vanilla', name: 'Vanilla with Pineapple', image: 'images/products/van-vanilla-with-pineapple.jpg', desc: 'Vanilla ice cream + pineapple topping', price: 40 },
  { id: 50, category: 'vanilla', name: 'Vanilla with Butterscotch', image: 'images/products/van-vanilla-with-butterscotch.jpg', desc: 'Vanilla ice cream + butterscotch', price: 40 },
  { id: 51, category: 'milkshake', name: 'Royal Vanilla', image: 'images/products/mil-royal-vanilla.jpg', desc: 'Classic vanilla milkshake', price: 60 },
  { id: 52, category: 'milkshake', name: 'Rose', image: 'images/products/mil-rose.jpg', desc: 'Refreshing rose flavored shake', price: 60 },
  { id: 53, category: 'milkshake', name: 'Pineapple', image: 'images/products/mil-pineapple.jpg', desc: 'Tangy pineapple milkshake', price: 60 },
  { id: 54, category: 'milkshake', name: 'Strawberry', image: 'images/products/mil-strawberry.jpg', desc: 'Fresh strawberry shake', price: 60 },
  { id: 55, category: 'milkshake', name: 'Black Current', image: 'images/products/mil-black-current.jpg', desc: 'Black current flavored shake', price: 60 },
  { id: 56, category: 'milkshake', name: 'Butter Scotch', image: 'images/products/mil-butter-scotch.jpg', desc: 'Caramel butterscotch shake', price: 60 },
  { id: 57, category: 'milkshake', name: 'Mango', image: 'images/products/mil-mango.jpg', desc: 'Fresh mango milkshake', price: 60 },
  { id: 58, category: 'milkshake', name: 'Oreo', image: 'images/products/mil-oreo.jpg', desc: 'Crushed Oreo milkshake', price: 80 },
  { id: 59, category: 'milkshake', name: 'Chocolate', image: 'images/products/mil-chocolate.jpg', desc: 'Rich chocolate milkshake', price: 80 },
  { id: 60, category: 'milkshake', name: 'Brownie', image: 'images/products/mil-brownie.jpg', desc: 'Brownie blended milkshake', price: 80 },
  { id: 61, category: 'milkshake', name: 'Chocopie', image: 'images/products/mil-chocopie.jpg', desc: 'Chocopie blended milkshake', price: 80 },
  { id: 62, category: 'milkshake', name: 'Hide & Seek', image: 'images/products/mil-hide-seek.jpg', desc: 'Hide & Seek cookie shake', price: 80 },
  { id: 63, category: 'milkshake', name: 'Perk', image: 'images/products/mil-perk.jpg', desc: 'Perk chocolate milkshake', price: 80 },
  { id: 64, category: 'milkshake', name: 'Munch', image: 'images/products/mil-munch.jpg', desc: 'Munch chocolate milkshake', price: 80 },
  { id: 65, category: 'milkshake', name: 'Kitkat', image: 'images/products/mil-kitkat.jpg', desc: 'Kitkat wafer milkshake', price: 80 },
  { id: 66, category: 'milkshake', name: '5 Star', image: 'images/products/mil-5-star.jpg', desc: '5 Star caramel milkshake', price: 80 },
  { id: 67, category: 'milkshake', name: 'Dairy Milk', image: 'images/products/mil-dairy-milk.jpg', desc: 'Dairy Milk chocolate shake', price: 80 },
  { id: 68, category: 'milkshake', name: 'Bournvita', image: 'images/products/mil-bournvita.jpg', desc: 'Classic Bournvita milkshake', price: 80 },
  { id: 69, category: 'milkshake', name: 'Snickers', image: 'images/products/mil-snickers.jpg', desc: 'Snickers loaded milkshake', price: 80 },
  { id: 70, category: 'milkshake', name: 'Rajbhog', image: 'images/products/mil-rajbhog.jpg', desc: 'Traditional rajbhog milkshake', price: 80 },
  { id: 71, category: 'milkshake', name: 'Kaju Mango', image: 'images/products/mil-kaju-mango.jpg', desc: 'Kaju & mango premium shake', price: 90 },
  { id: 72, category: 'milkshake', name: 'Kaju Anjeer', image: 'images/products/mil-kaju-anjeer.jpg', desc: 'Kaju & anjeer premium shake', price: 90 },
  { id: 73, category: 'milkshake', name: 'Sitafal (Seasonal)', image: 'images/products/mil-sitafal-seasonal.jpg', desc: 'Seasonal sitafal milkshake', price: 90 },
  { id: 74, category: 'milkshake', name: 'Oreo With Brownie', image: 'images/products/mil-oreo-with-brownie.jpg', desc: 'Oreo + brownie combo shake', price: 90 },
  { id: 75, category: 'milkshake', name: 'Oreo With Chocopie', image: 'images/products/mil-oreo-with-chocopie.jpg', desc: 'Oreo + chocopie combo shake', price: 90 },
  { id: 76, category: 'milkshake', name: 'Oreo With Hide & Seek', image: 'images/products/mil-oreo-with-hide-seek.jpg', desc: 'Oreo + hide & seek combo shake', price: 90 },
  { id: 77, category: 'milkshake', name: 'Oreo With Kitkat', image: 'images/products/mil-oreo-with-kitkat.jpg', desc: 'Oreo + kitkat combo shake', price: 90 },
  { id: 78, category: 'milkshake', name: 'Oreo With Munch', image: 'images/products/mil-oreo-with-munch.jpg', desc: 'Oreo + munch combo shake', price: 90 },
  { id: 79, category: 'milkshake', name: 'Oreo With Dairy Milk', image: 'images/products/mil-oreo-with-dairy-milk.jpg', desc: 'Oreo + dairy milk combo shake', price: 90 },
  { id: 80, category: 'milkshake', name: 'Oreo With 5 Star', image: 'images/products/mil-oreo-with-5-star.jpg', desc: 'Oreo + 5 star combo shake', price: 90 },
  { id: 81, category: 'milkshake', name: 'Brownie With Chocopie', image: 'images/products/mil-brownie-with-chocopie.jpg', desc: 'Brownie + chocopie combo shake', price: 90 },
  { id: 82, category: 'milkshake', name: 'Brownie With Perk', image: 'images/products/mil-brownie-with-perk.jpg', desc: 'Brownie + perk combo shake', price: 90 },
  { id: 83, category: 'milkshake', name: 'Brownie With Kitkat', image: 'images/products/mil-brownie-with-kitkat.jpg', desc: 'Brownie + kitkat combo shake', price: 90 },
  { id: 84, category: 'milkshake', name: 'Brownie With Munch', image: 'images/products/mil-brownie-with-munch.jpg', desc: 'Brownie + munch combo shake', price: 90 },
  { id: 85, category: 'milkshake', name: 'Brownie With Hide & Seek', image: 'images/products/mil-brownie-with-hide-seek.jpg', desc: 'Brownie + hide & seek combo', price: 90 },
  { id: 86, category: 'milkshake', name: 'Brownie With Dairy Milk', image: 'images/products/mil-brownie-with-dairy-milk.jpg', desc: 'Brownie + dairy milk combo', price: 90 },
  { id: 87, category: 'milkshake', name: 'Brownie With 5 Star', image: 'images/products/mil-brownie-with-5-star.jpg', desc: 'Brownie + 5 star combo shake', price: 90 },
  { id: 88, category: 'milkshake', name: 'Hide & Seek With Perk', image: 'images/products/mil-hide-seek-with-perk.jpg', desc: 'Hide & seek + perk combo shake', price: 90 },
  { id: 89, category: 'milkshake', name: 'Hide & Seek With Kitkat', image: 'images/products/mil-hide-seek-with-kitkat.jpg', desc: 'Hide & seek + kitkat combo', price: 90 },
  { id: 90, category: 'milkshake', name: 'Hide & Seek With Munch', image: 'images/products/mil-hide-seek-with-munch.jpg', desc: 'Hide & seek + munch combo', price: 90 },
  { id: 91, category: 'milkshake', name: 'Hide & Seek With Dairy Milk', image: 'images/products/mil-hide-seek-with-dairy-milk.jpg', desc: 'Hide & seek + dairy milk combo', price: 90 },
  { id: 92, category: 'milkshake', name: 'Hide & Seek With 5 Star', image: 'images/products/mil-hide-seek-with-5-star.jpg', desc: 'Hide & seek + 5 star combo', price: 90 },
  { id: 93, category: 'milkshake', name: 'Chocopie With Perk', image: 'images/products/mil-chocopie-with-perk.jpg', desc: 'Chocopie + perk combo shake', price: 90 },
  { id: 94, category: 'milkshake', name: 'Chocopie With Hide & Seek', image: 'images/products/mil-chocopie-with-hide-seek.jpg', desc: 'Chocopie + hide & seek combo', price: 90 },
  { id: 95, category: 'milkshake', name: 'Chocopie With Kitkat', image: 'images/products/mil-chocopie-with-kitkat.jpg', desc: 'Chocopie + kitkat combo shake', price: 90 },
  { id: 96, category: 'milkshake', name: 'Chocopie With Dairy Milk', image: 'images/products/mil-chocopie-with-dairy-milk.jpg', desc: 'Chocopie + dairy milk combo', price: 90 },
  { id: 97, category: 'milkshake', name: 'Chocopie With Munch', image: 'images/products/mil-chocopie-with-munch.jpg', desc: 'Chocopie + munch combo shake', price: 90 },
  { id: 98, category: 'milkshake', name: 'Chocopie With 5 Star', image: 'images/products/mil-chocopie-with-5-star.jpg', desc: 'Chocopie + 5 star combo shake', price: 90 },
  { id: 99, category: 'milkshake', name: 'Perk With Kitkat', image: 'images/products/mil-perk-with-kitkat.jpg', desc: 'Perk + kitkat combo shake', price: 90 },
  { id: 100, category: 'milkshake', name: 'Perk With Munch', image: 'images/products/mil-perk-with-munch.jpg', desc: 'Perk + munch combo shake', price: 90 },
  { id: 101, category: 'milkshake', name: 'Perk With Dairy Milk', image: 'images/products/mil-perk-with-dairy-milk.jpg', desc: 'Perk + dairy milk combo shake', price: 90 },
  { id: 102, category: 'milkshake', name: 'Perk With 5 Star', image: 'images/products/mil-perk-with-5-star.jpg', desc: 'Perk + 5 star combo shake', price: 90 },
  { id: 103, category: 'milkshake', name: 'Kitkat With Dairy Milk', image: 'images/products/mil-kitkat-with-dairy-milk.jpg', desc: 'Kitkat + dairy milk combo shake', price: 90 },
  { id: 104, category: 'milkshake', name: 'Kitkat With 5 Star', image: 'images/products/mil-kitkat-with-5-star.jpg', desc: 'Kitkat + 5 star combo shake', price: 90 },
  { id: 105, category: 'milkshake', name: 'Munch With Dairy Milk', image: 'images/products/mil-munch-with-dairy-milk.jpg', desc: 'Munch + dairy milk combo shake', price: 90 },
  { id: 106, category: 'milkshake', name: 'Munch With 5 Star', image: 'images/products/mil-munch-with-5-star.jpg', desc: 'Munch + 5 star combo shake', price: 90 },
  { id: 107, category: 'milkshake', name: 'Dairy Milk With 5 Star', image: 'images/products/mil-dairy-milk-with-5-star.jpg', desc: 'Dairy milk + 5 star combo', price: 90 },
  { id: 108, category: 'milkshake', name: 'Satyanarayan Special', image: 'images/products/mil-satyanarayan-special.jpg', desc: 'Signature premium milkshake', price: 110 },
  { id: 109, category: 'thickshake', name: 'Rose', image: 'images/products/thi-rose.jpg', desc: 'Thick & creamy rose shake', price: 80 },
  { id: 110, category: 'thickshake', name: 'Royal Vanilla', image: 'images/products/thi-royal-vanilla.jpg', desc: 'Extra thick vanilla shake', price: 80 },
  { id: 111, category: 'thickshake', name: 'Pineapple', image: 'images/products/thi-pineapple.jpg', desc: 'Thick pineapple shake', price: 80 },
  { id: 112, category: 'thickshake', name: 'Strawberry', image: 'images/products/thi-strawberry.jpg', desc: 'Thick strawberry shake', price: 80 },
  { id: 113, category: 'thickshake', name: 'Black Current', image: 'images/products/thi-black-current.jpg', desc: 'Thick black current shake', price: 80 },
  { id: 114, category: 'thickshake', name: 'Butter Scotch', image: 'images/products/thi-butter-scotch.jpg', desc: 'Thick butterscotch shake', price: 80 },
  { id: 115, category: 'thickshake', name: 'Mango', image: 'images/products/thi-mango.jpg', desc: 'Thick mango shake', price: 80 },
  { id: 116, category: 'thickshake', name: 'Chocopie', image: 'images/products/thi-chocopie.jpg', desc: 'Thick chocopie shake', price: 80 },
  { id: 117, category: 'thickshake', name: 'Brownie', image: 'images/products/thi-brownie.jpg', desc: 'Thick brownie shake', price: 80 },
  { id: 118, category: 'thickshake', name: 'Oreo', image: 'images/products/thi-oreo.jpg', desc: 'Thick Oreo shake', price: 80 },
  { id: 119, category: 'thickshake', name: 'Chocolate', image: 'images/products/thi-chocolate.jpg', desc: 'Thick chocolate shake', price: 80 },
  { id: 120, category: 'thickshake', name: 'Perk', image: 'images/products/thi-perk.jpg', desc: 'Thick Perk shake', price: 80 },
  { id: 121, category: 'thickshake', name: 'Hide & Seek', image: 'images/products/thi-hide-seek.jpg', desc: 'Thick Hide & Seek shake', price: 80 },
  { id: 122, category: 'thickshake', name: 'Kitkat', image: 'images/products/thi-kitkat.jpg', desc: 'Thick Kitkat shake', price: 80 },
  { id: 123, category: 'thickshake', name: 'Munch', image: 'images/products/thi-munch.jpg', desc: 'Thick Munch shake', price: 80 },
  { id: 124, category: 'thickshake', name: '5 Star', image: 'images/products/thi-5-star.jpg', desc: 'Thick 5 Star shake', price: 80 },
  { id: 125, category: 'thickshake', name: 'Dairy Milk', image: 'images/products/thi-dairy-milk.jpg', desc: 'Thick Dairy Milk shake', price: 80 },
  { id: 126, category: 'thickshake', name: 'Snickers', image: 'images/products/thi-snickers.jpg', desc: 'Thick Snickers shake', price: 80 },
  { id: 127, category: 'thickshake', name: 'Kaju Mango', image: 'images/products/thi-kaju-mango.jpg', desc: 'Premium kaju mango thick shake', price: 120 },
  { id: 128, category: 'thickshake', name: 'Kaju Anjeer', image: 'images/products/thi-kaju-anjeer.jpg', desc: 'Premium kaju anjeer thick shake', price: 120 },
  { id: 129, category: 'coldcoffee', name: 'Cold Coffee', image: 'images/products/col-cold-coffee.jpg', desc: 'Classic chilled cold coffee', price: 70 },
  { id: 130, category: 'coldcoffee', name: 'Cold Coffee with Ice-Cream', image: 'images/products/col-cold-coffee-with-ice-cream.jpg', desc: 'Cold coffee topped with ice cream', price: 80 },
  { id: 131, category: 'coldcoffee', name: 'Cold Coffee with Oreo', image: 'images/products/col-cold-coffee-with-oreo.jpg', desc: 'Cold coffee blended with Oreo', price: 80 },
  { id: 132, category: 'coldcoffee', name: 'Cold Coffee with Brownie', image: 'images/products/col-cold-coffee-with-brownie.jpg', desc: 'Cold coffee with brownie chunks', price: 80 },
  { id: 133, category: 'coldcoffee', name: 'Cold Coffee with Perk', image: 'images/products/col-cold-coffee-with-perk.jpg', desc: 'Cold coffee with Perk chocolate', price: 80 },
  { id: 134, category: 'coldcoffee', name: 'Cold Coffee with Kitkat', image: 'images/products/col-cold-coffee-with-kitkat.jpg', desc: 'Cold coffee with Kitkat crunch', price: 80 },
  { id: 135, category: 'coldcoffee', name: 'Cold Coffee with Munch', image: 'images/products/col-cold-coffee-with-munch.jpg', desc: 'Cold coffee with Munch chocolate', price: 80 },
  { id: 136, category: 'coldcoffee', name: 'Cold Coffee with 5 Star', image: 'images/products/col-cold-coffee-with-5-star.jpg', desc: 'Cold coffee with 5 Star caramel', price: 80 },
  { id: 137, category: 'coldcoffee', name: 'Cold Coffee with Dairy Milk', image: 'images/products/col-cold-coffee-with-dairy-milk.jpg', desc: 'Cold coffee with Dairy Milk', price: 80 },
  { id: 138, category: 'coldcoffee', name: 'Cold Coffee with Snickers', image: 'images/products/col-cold-coffee-with-snickers.jpg', desc: 'Cold coffee with Snickers', price: 80 },
  { id: 139, category: 'coldcoffee', name: 'Cold Coffee with Chocopie', image: 'images/products/col-cold-coffee-with-chocopie.jpg', desc: 'Cold coffee with Chocopie', price: 80 },
  { id: 140, category: 'coldcoffee', name: 'Cold Coffee with Hide & Seek', image: 'images/products/col-cold-coffee-with-hide-seek.jpg', desc: 'Cold coffee with Hide & Seek', price: 80 },
  { id: 141, category: 'coldcoffee', name: 'Satyanarayan Special Coffee', image: 'images/products/col-satyanarayan-special-coffee.jpg', desc: 'Signature premium cold coffee', price: 100 },
];
